### ISSUE TITLE
Bug no calculo dos correios.

### ISSUE THREAD

**Issue by sergiomendonca** [intelipost/magento2-tracking#1]
Se tenho 3 produtos cada um tem 11kg.
O correios aceita até 30kg.

Caso eu adicione 3 produtos, ele deveria encontrar alguma forma de ao menos colocar os 3 em caixas diferentes e calcular o frete. Ao contrario disso o mesmo apresenta o erro fatal que compromete toda compra:

Segue o bug:

<img width="1356" alt="captura de tela 2018-10-15 as 13 40 36" src="https://user-images.githubusercontent.com/34236548/46965087-3b0e8a00-d080-11e8-81f2-b0350fd21729.png">

**Comment by sergiomendonca** [comment]
Em resumo, passou de 30kg (produto*quantidade), crash no sistema. Se for menor não apresenta problemas.

**Comment by rogerioms** [comment]
@sergiomendonca Muito obrigado pelo report. 
Esta questão faz parte do nosso módulo de calculo de frete, não do modulo de tracking. 

Poderia abrir esta issue no outro repositório? 
https://github.com/intelipost/magento2-quote
